### ISSUE TITLE
"transient local" required on both ends

### ISSUE THREAD

**Issue by BrannonKing** [tocinc/rmw_coredx#12]
I recognize that it is typical to require the same QoS settings on both subscriber and receiver. However, I believe some forgiveness is in order in this regard. DDS and ROS's QoS support the idea of publishers that send their most-recent data to each new subscriber automatically. The ROS QoS uses "durability" for the name of this feature. You can set your QoS to a durability of "transient local" to keep data in RAM for sending it to each new subscriber. When using CoreDX, I'm required to specify "transient local" on the receiver as well.  I find that somewhat annoying. I can understand why a "reliable" connection would need to be specified on both ends, and with the rolling history setting it seems you would need to just use the smallest value from either end. "Durability", though is all about what the publisher does with new connections. Thoughts?

**Comment by ClarkTucker** [comment]
From a DDS perspective, some readers may be interested in 'historical' data (persisted at the writer for late joining readers via the durability qos), and some readers may not want the historical data, even it is available from the writer.  The ability to specify the durability at the reader is a feature that allows a refinement of the persistence behavior.
