### ISSUE TITLE
wifi performance

### ISSUE THREAD

**Issue by SecretaryBirds** [tocinc/rmw_coredx#13]
performance of message traffic using ROS2 on CoreDX is poor.
see this thread for some details: https://discourse.ros.org/t/astra-driver-for-ros2/1894/13

**Comment by BrannonKing** [comment]
This was addressed somewhat in 4.0.20. Works for large messages:
Option 1: CoreDX 4.0.16/20 + Reliable + IPv6 + Multicast Data On
Option 2: CoreDX 4.0.16/20 + Reliable + IPv4/6 + Multicast Data Off
Option 3: CoreDX 4.0.20 + BestEffort + IPv4/6 + Multicast Data Off
