### ISSUE TITLE
ROS2 Beta2 released, and this code is incompatible with the new API

### ISSUE THREAD

**Issue by SecretaryBirds** [tocinc/rmw_coredx#14]
The API has changed on some things and if you try to compile this rmw_coredx with the new Beta2 release, it fails to build.

**Comment by ClarkTucker** [comment]
I've updated so it now compiles OK against the ros2 beta2.

**Comment by SecretaryBirds** [comment]
Looks good. 1 follow-up question: which ros2.repos file did you use to build against?
We have a custom one, but it seemed to work even though I didn't expect it to.
I pulled the `coredx` branch of the `rms_implementation` repo, which doesn't have the latest API, and it still worked.
I'm a bit confused....
