### ISSUE TITLE
Working with Ros2 Ardent Release

### ISSUE THREAD

**Issue by nate-jackson** [tocinc/rmw_coredx#17]
I have seen recent work done to get the middleware complying with the new Ros2 release (ardent).

We tried building with this version and everything compiles. When we run python nodes they work fine. But when we run cpp nodes we get a runtime linker error no matter which node we try to run. The error is: 
```
platform@beast2:~/ros2_with_new_coredx_src$ ros2 run demo_nodes_cpp talker
/home/platform/ros2_with_new_coredx_src/install/lib/demo_nodes_cpp/talker: symbol lookup error: /home/platform/ros2_with_new_coredx_src/install/lib/librcl_interfaces__rosidl_typesupport_coredx_cpp.so: undefined symbol: _ZN3DDS3rpc15RequesterParams12service_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

Perhaps this is a nonissue though if things just aren't ready yet, which is fine. Is everything in this rmw_coredx implementation ready? Or is there still some work in progress to get it ready?

**Comment by ClarkTucker** [comment]
We're still working on broad platform support.  It would be very helpful if you could provide information about your environment, for example:

* compiler version
* coredx version (including OS/compiler version)
* LD_LIBRARY_PATH 

Thanks!

**Comment by nate-jackson** [comment]
Awesome thanks for the update.

gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

COREDX_VERSION="4.1.0"
COREDX_HOST="Linux_2.6_x86_64_gcc43"
COREDX_TARGET="Linux_2.6_x86_64_gcc43"

LD_LIBRARY_PATH="/home/platform/ros2_with_new_coredx_src/install/lib:/home/platform/ros2_with_new_coredx_src/coredx-4.1.0/target/Linux_2.6_x86_64_gcc43/lib"

**Comment by ClarkTucker** [comment]
Thanks for this.
I think the issue is due to a difference between the compilers used (gcc54 vs gcc43).  [I think we ran into this before?]  I thought we had some special flags in the rmw_coredx build system to handle this case, but maybe they didn't get updated correctly -- we'll look into that.

In the meantime, do you have the coredx build "Linux_2.6_x86_64_gcc5"?  This one will probably link OK...

**Comment by nate-jackson** [comment]
Yes this now works great. Thank you~
